### ISSUE TITLE
Heavy core drop chance needs rebalancing?

### ISSUE THREAD

**Issue by B-Wither** [Jusey1/TrialsChambersBackport#10]
I opened 50 ominous vaults in creative, none of them dropped heavy core. Yeah I have seen once when I tried to open it too many times, but in survival how many chambers I have to travel to obtain mace?

**Comment by Jusey1** [comment]
It's a bit rarer than officially because I made Vaults have a cooldown of 10 minutes instead of once per player. However, opening 50 and getting none is extremely bad luck, or should be... I double checked and holy moly, I accidentally gave too much weight to diamond armor from the rare drop table so you basically get that like 95% of the time, which makes the heavy core much rarer than intended. Am fixing. Will be doing the same with enchanted iron armor droprates from the normal vaults. Gonna tune them both down in the rare drop table to give a better chance for the most valuable drop in both (heavy core for ominous and trident for normal).
